version: "3.9"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      LANG: C.UTF-8
    volumes:
      - ./volumes:/var/lib/mysql:cached
